DK.UI.Web/Controllers/EmployeSalaryController.cs
using AutoMapper;
using DK.ApplicationCore.DTOs;
using DK.ApplicationCore.Entity;
using DK.ApplicationCore.Interfaces.Services;
using DK.UI.Web.Controllers.Untils;
using DK.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DK.UI.Web.Controllers
{
    public class EmployeSalaryController : Controller
    {

        private readonly IEmployeMasterSalaryService _employeMasterSalaryService;
        private readonly ICalculateEmployesSalaryService _calculateEmployesSalaryService;
        private readonly IMapper _mapper;
        private EmployeMasterSalary _employeMasterSalary;

        public EmployeSalaryController(IEmployeMasterSalaryService employeMasterSalaryService, IMapper mapper, ICalculateEmployesSalaryService calculateEmployesSalaryService)
        {
            this._employeMasterSalaryService = employeMasterSalaryService;
            this._calculateEmployesSalaryService = calculateEmployesSalaryService;
            this._mapper = mapper;
        }

        public async Task<ActionResult> Search(string code)
        {
            if (string.IsNullOrEmpty(code)) throw new ArgumentException("Value cannot be null or empty.", nameof(code));
            var dataEmploye = (await _employeMasterSalaryService.GetEmployeMasterSalaries()).Find(l => l.EmployeCode == code);
            if (dataEmploye == null)
            {
                return PartialView("Details", new EmployeGeneralDataDto
                {
                    Birthday = new DateTime(1900, 01, 01),
                    EmployeName = "N/A",
                    EmployeCode = "N/A",
                    EmployeSurname = "N/A",
                    BeginDate = new DateTime(1900, 01, 01),
                    Division = "N/A",
                    Grade = 0,
                    IdentificationNumber = "N/A",
                    Position = "N/A"

                });
            }
            var dataEmployeRetun = _mapper.Map<EmployeGeneralDataDto>(dataEmploye);
            return PartialView("Details", dataEmployeRetun);
        }

        // GET: EmployeSalaryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeSalaryController/Create
        [HttpPost]
        public async Task<ActionResult> Create(EmployeGeneralDataDto employeGeneralDataDto)
        {
            try
            {
                if (employeGeneralDataDto.EmployeCode == null)
                {
                    return Json(new { Passed = false, PageResult = "Codigo de empleado Null o vacio." });
                }
                if (!(await _employeMasterSalaryService.GetEmployeMasterSalaries()).Where(l => l.EmployeCode == employeGeneralDataDto.EmployeCode).Any())
                {
                    return Json(new { Passed = false, PageResult = "Codigo del empleado no existe." });
                }
                if (employeGeneralDataDto.LinesData == null)
                {
                    return Json(new { Passed = false, PageResult = "Registre al menos un detalle economico." });
                }

                var employeMasterSalaryData = employeGeneralDataDto.LinesData.Select(async l => new EmployeMasterSalaryDto
                {
                    EmployeCode = employeGeneralDataDto.EmployeCode,
                    EmployeName = employeGeneralDataDto.EmployeName,
                    EmployeSurname = employeGeneralDataDto.EmployeSurname,
                    Birthday = employeGeneralDataDto.Birthday,
                    BeginDate = employeGeneralDataDto.BeginDate,
                    IdentificationNumber = employeGeneralDataDto.IdentificationNumber,
                    Division = employeGeneralDataDto.Division,
                    Office = employeGeneralDataDto.Office,
                    Position = employeGeneralDataDto.Position,
                    Grade = employeGeneralDataDto.Grade,
                    BaseSalary = l.BaseSalary,
                    Commission = l.Commission,
                    CompensationBonus = l.CompensationBonus,
                    Contributions = l.Contributions,
                    Month = l.Month,
                    Year = l.Year,
                    ProductionBonus = l.ProductionBonus,
                    OtherIncome = await _calculateEmployesSalaryService.CalculateOtherIncome(l.BaseSalary, l.Commission),
                    TotalSalary = await _calculateEmployesSalaryService.CalculateTotalSalary(l.BaseSalary, l.ProductionBonus, l.CompensationBonus, (await _calculateEmployesSalaryService.CalculateOtherIncome(l.BaseSalary, l.Commission)), l.Contributions)

                }).Select(l => l.Result).ToList();

                var valideYearAndMonthData = (await _employeMasterSalaryService.GetEmployeMasterSalaries())

                    .Join(employeMasterSalaryData, a => a.EmployeCode, b => b.EmployeCode, (a, b) => new { DbData = a, newData = b })
                    .Where(l => l.DbData.Year == l.newData.Year && l.DbData.Month == l.newData.Month).ToList();
                if (valideYearAndMonthData.Any())
                {
                    var firtDuplicateDate = valideYearAndMonthData.FirstOrDefault();
                    if (firtDuplicateDate != null)
                        return Json(new
                        {
                            Passed = false,
                            PageResult =
                                $"El mes {firtDuplicateDate.newData.Month} para el año {firtDuplicateDate.newData.Year} del empleado {firtDuplicateDate.DbData.EmployeCode} ya esta registrado."
                        });
                }
                var dataToCreate = _mapper.Map<List<EmployeMasterSalary>>(employeMasterSalaryData);
                var result = await _employeMasterSalaryService.Create(dataToCreate);

                if (result.Passed)
                {
                    return Json(new { Passed = true, PageResult = "" });
                }
                else
                {
                    return Json(new { Passed = false, PageResult = result.MessageError });
                }

            }
            catch (Exception)
            {
                return Json(new { Passed = false, PageResult = $"Ocurrio un error inesperado comuniquese con el administrador del sistema." });
            }
        }

        // GET: EmployeSalaryController/Edit/5
        public ActionResult Successful()
        {
            return View();
        }

        public ActionResult ErrorView(string message)
        {
            var actionResult = View(new ErrorViewModel {MessageError = message});
            return actionResult;
        }

        public ActionResult CalculationMasterViews()
        {
            return View();
        }

        public async Task<ActionResult> CalculationMasterDetailsViews(string option, string employeCode)
        {
            if (option == null)
            {
                return PartialView(new List<CalculationsEmployesSalaryViewDtos>());
            }


            var employesCatalog = (await _employeMasterSalaryService.GetEmployeMasterSalaries())
                .GroupBy(l => new { l.EmployeCode, l.EmployeName, l.EmployeSurname, l.Division, l.Grade, l.Position, l.BeginDate, l.Birthday, l.IdentificationNumber, l.Office })
                .Select(l => new { l.Key, Year = l.Max(v => v.Year), Month = l.Where(v => v.Year == l.Max(employeMasterSalary => employeMasterSalary.Year)).Max(employeMasterSalary => employeMasterSalary.Month), DataGrouping = l.Where(f => f.Year == l.Max(employeMasterSalary => employeMasterSalary.Year)) })
                .Select((l, i) =>
                {
                    {
                        bool Func(EmployeMasterSalary x)
                        {
                            return x.Month == l.Month;
                        }


                        _employeMasterSalary = l.DataGrouping.FirstOrDefault(Func);
                        if (_employeMasterSalary != null)
                            return new
                            {
                                Id = i,
                                l.Key.EmployeCode,
                                l.Key.EmployeName,
                                l.Key.EmployeSurname,
                                l.Key.BeginDate,
                                l.Key.Grade,
                                BirthDay = l.Key.BeginDate,
                                Divicion = l.Key.Division,
                                l.Key.IdentificationNumber,
                                l.Key.Position,
                                BaseSalary = l.DataGrouping.Any()
                                    ? _employeMasterSalary.BaseSalary
                                    : 0,
                                Commission = l.DataGrouping.Any()
                                    ? _employeMasterSalary.Commission
                                    : 0,
                                CompensationBonus = l.DataGrouping.Any()
                                    ? _employeMasterSalary.CompensationBonus
                                    : 0,
                                ProductionBonus = l.DataGrouping.Any()
                                    ? _employeMasterSalary.ProductionBonus
                                    : 0,
                                Contributions = l.DataGrouping.Any()
                                    ? _employeMasterSalary.Contributions
                                    : 0,
                                l.Key.Office
                            };
                    }

                    return null;
                });
            var catalog = employesCatalog.ToList();
            var modelEmploye = catalog.FirstOrDefault(l => l.EmployeCode == employeCode);

            Func<CalculationsEmployesSalaryViewDtos, bool> filterData;
            switch ((FilterGrouping)Convert.ToInt32(option))
            {

DK.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
    <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap3-editable/js/bootstrap-editable.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Marshalls LLC</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrapTable/bootstrap-table.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap3-editable/css/bootstrap-editable.css" />

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marshalls LLC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Maestro de Salarios
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Create","EmployeSalary")">Crear</a>
                            <a class="dropdown-item" href="@Url.Action("CalculationMasterViews","EmployeSalary")">Consulta General</a>

                            <a class="dropdown-item" href="@Url.Action("LastSalaries","EmployeSalary")">Consulta Ultimos 3 Salarios</a>
                        </div>
                    </li>

                </ul>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <div class="preventReflow">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DK.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>